name: Build YouMod dylib
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH Environment Variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Setup Theos
        run: |
          git clone --quiet --depth=1 --recurse-submodules https://github.com/roothide/theos.git
          git clone --quiet --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS26.5.sdk
          git checkout --quiet
          mv *.sdk "$THEOS/sdks"

      - name: Clone headers
        run: |
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git "$THEOS/include/YouTubeHeader"
          git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git "$THEOS/include/PSHeader"

      - name: Fix Theos od broken pipe issue
        run: sed -i '' 's/od -c "$i" | head/od -c "$i" 2>\/dev\/null | head/g' $THEOS/bin/convert_xml_plist.sh || true

      - name: Build YouMod
        run: make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Collect dylib
        run: |
          mkdir -p dist
          find .theos packages -name 'YouMod.dylib' -exec cp {} dist/ \;
          ls -la dist

      - uses: actions/upload-artifact@v4
        with:
          name: YouMod-dylib
          path: dist/YouMod.dylib
